git:
  depth: 3 # Fetch 3 last commit, clone is lighter

language: php

php:
  - 7.1

services:
  - mysql

cache:
  directories:
    - app/vendor

before_install:
  - mysql -e 'CREATE DATABASE blog;'
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - cd app

install:
  - composer install --no-interaction # Need to be under install directive to cache vendor

# Setup project
before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate

# Execute test after setup
script:
  - php vendor/bin/phpunit
  - php vendor/bin/behat
  - php vendor/bin/phploc app/


after_success:
  - test $TRAVIS_BRANCH = "master"
  - mkdir ~/.ssh
  - echo $SSH_PUBLIC > ~/.ssh/id_rsa.pub
  - chmod 644  ~/.ssh/id_rsa.pub
  - chmod 600  ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh -o "StrictHostKeyChecking=no" -p 6622 $SSH_USER@$SSH_HOST "git clone https://github.com/AlexBDev/laravel-blog-jenkins.git; cd laravel-blog-jenkins; git pull origin master; source user-permission.sh; docker-compose up -d; docker-compose exec -T php composer install"

