git:
  depth: 3

language: php

php:
  - 7.1

services:
  - mysql

cache: vendor

before_install:
  - mysql -e 'CREATE DATABASE blog;'

before_script:
  - cd app
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - php vendor/bin/phpunit
  - php vendor/bin/behat
