git:
  depth: 3 # Fetch 3 last commit, clone is lighter

language: php

php:
  - 7.1

services:
  - mysql

cache:
  directories:
    - app/vendor

before_install:
  - wget http://rocketeer.autopergamene.eu/versions/rocketeer.phar
  - chmod +x rocketeer.phar
  - mv rocketeer.phar /home/travis/rocketeer
  - /home/travis/rocketeer -v
  - mysql -e 'CREATE DATABASE blog;'
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - cd app

install:
  - composer install --no-interaction # Need to be under install directive to cache vendor

# Setup project
before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate

# Execute test after setup
script:
  - php vendor/bin/phpunit
  - php vendor/bin/behat
  - ./vendor/bin/phpcs # Launch CodeSniffer tests (with phpcs.xml file config)
  - php vendor/bin/phploc app/

after_success:
  - mkdir ~/.ssh
  - echo $SSH_PUBLIC > ~/.ssh/id_rsa.pub
  - chmod 644  ~/.ssh/id_rsa.pub
  - chmod 600  ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"

deploy:
  provider: script
  script: /home/travis/rocketeer deploy
  on:
    branch: master
