git:
  depth: 3

language: php

php:
  - 7.1

services:
  - mysql

cache:
  directories:
    - /home/travis/vendor

before_install:
  - mysql -e 'CREATE DATABASE blog;'


install:
  - composer install --no-interaction

before_script:
  - cd app
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate

script:
  - cd app
  - php vendor/bin/phpunit
  - php vendor/bin/behat
