version: "3.1"
services:
    jenkins:
        build:
            context: ./dockerfiles/jenkins
        volumes:
            - jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8080:8080"
            - "5000:5000"

volumes:
    jenkins-data: